name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
jobs:

  ftpdeploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: hgondie.devwebgarneau/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.hgondie.devwebgarneau.com
        username: hgondie
        password: ${{ secrets.ftp_password }}
        
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
           token: ${{ secrets.DEPLOY_SECRETS }}
           projectToken: ${{ secrets.CHROMATIC_TOKEN  }}
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run chromatic

