name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
           token: ${{ secrets.DEPLOY_SECRETS }}
           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - run: npm i
      - run: npm run build
      - run: npm test
      - run: npm run chromatic
