name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
      
jobs:

  ftpdeploy:
    name: Deploy-ftp
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@v2
    
      with:
        server: ftp.hgondie.devwebgarneau.com
        username: hgondie
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        port: 21
        
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
           token: ${{ secrets.DEPLOY_SECRETS }}
           projectToken: ${{ secrets.CHROMATIC_TOKEN  }}
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run chromatic

